headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "Z:\\AI_ImageGen\\ComfyUI\\card_generator\\public"
publishOrigin = "config"
commandOrigin = "config"
base = "Z:\\AI_ImageGen\\ComfyUI\\card_generator"
command = "echo 'No build step required for static site'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.png"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.jpg"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]